traits:
  - bombastic
  - scrappy
  - nimble
  - argumentative
  - grumpy
  - drunk
  - overly friendly
  - touchy
  - flirtatious
  - ponderous
  - inquisitive
  - skeptical
  - ruminating
  - articulate
  - ejaculatory (in terms of sound)
  - timid
  - bold
  - dubious
  - overly sympathetic
  - boorish
  - feckless
  - nefarious
  - honorable
  - spasmodic

races:
  - orc
  - half-orc
  - human
  - elf
  - half-elf
  - halfling
  - dragonborn
  - tiefling
  - dwarf
  - gnome

dnd_classes:
  - fighter
  - rogue
  - wizard
  - sorceror
  - druid
  - cleric
  - bard
  - monk
  - warlock
  - paladin

npc_stats_by_challenge_rating:
  'Headers': [proficiency_bonus, armor_class, hit_points, attack_bonus, damage_per_round, save_dc]
  '0': [2, 13, 1..6, 3, 1..2, 13]
  '1/8': [2, 13, 7..35, 3, 2..3, 13]
  '1/4': [2, 13, 36..49, 3, 4..5, 13]
  '1/2': [2, 13, 50..70, 3, 6..8, 13]
  '1': [2, 13, 71..85, 3, 9..14, 13]
  '2': [2, 13, 16..100, 3, 15..20, 13]
